# Generated by Django 4.2.16 on 2025-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_file',
            field=models.FileField(null=True, upload_to='models/'),
        ),
    ]
