# Generated by Django 4.2.16 on 2025-02-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model_model_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flatten',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
                ('input_x', models.PositiveIntegerField(default=256)),
                ('input_y', models.PositiveIntegerField(default=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
        migrations.AddField(
            model_name='layer',
            name='activation_function',
            field=models.CharField(choices=[('relu', 'ReLU'), ('softmax', 'Softmax')], default='', max_length=100),
        ),
    ]
