# Generated by Django 4.2.16 on 2025-02-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flatten_layer_activation_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlattenLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
                ('input_x', models.PositiveIntegerField(blank=True, default=256, null=True)),
                ('input_y', models.PositiveIntegerField(blank=True, default=256, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
        migrations.DeleteModel(
            name='Flatten',
        ),
    ]
