# Generated by Django 4.2.16 on 2025-02-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dropoutlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxPooling2DLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
        migrations.AddField(
            model_name='conv2dlayer',
            name='input_x',
            field=models.PositiveIntegerField(blank=True, default=256, null=True),
        ),
        migrations.AddField(
            model_name='conv2dlayer',
            name='input_y',
            field=models.PositiveIntegerField(blank=True, default=256, null=True),
        ),
        migrations.AddField(
            model_name='conv2dlayer',
            name='input_z',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
