# Generated by Django 4.2.16 on 2025-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dataset_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='element',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
