# Generated by Django 4.2.16 on 2025-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maxpooling2dlayer_conv2dlayer_input_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattenlayer',
            name='input_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flattenlayer',
            name='input_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
