# Generated by Django 4.2.16 on 2025-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_dataset_currentidx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='label',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
