# Generated by Django 4.2.16 on 2025-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_conv2dlayer_input_x_alter_conv2dlayer_input_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_z',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
