# Generated by Django 4.2.16 on 2025-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_conv2dlayer_input_x_alter_conv2dlayer_input_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxpooling2dlayer',
            name='pool_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_y',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conv2dlayer',
            name='input_z',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flattenlayer',
            name='input_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flattenlayer',
            name='input_y',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D'), ('maxpooling2d', 'MaxPooling2D'), ('flatten', 'Flatten'), ('dropout', 'Dropout')], default='dense', max_length=100),
        ),
    ]
