# Generated by Django 4.2.16 on 2025-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_maxpooling2dlayer_pool_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaxPooling2DLayer',
            new_name='MaxPool2DLayer',
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D'), ('maxpool2d', 'MaxPool2d'), ('flatten', 'Flatten'), ('dropout', 'Dropout')], default='dense', max_length=100),
        ),
    ]
