# Generated by Django 4.2.16 on 2025-02-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_maxpooling2dlayer_maxpool2dlayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropoutlayer',
            old_name='probability',
            new_name='rate',
        ),
    ]
