# Generated by Django 4.2.16 on 2025-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_model_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
