# Generated by Django 4.2.16 on 2025-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_model_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='downloaders',
            field=models.ManyToManyField(blank=True, related_name='downloaded_models', to='api.profile'),
        ),
    ]
