# Generated by Django 4.2.16 on 2025-02-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dataset_dataset_type_alter_dataset_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='api.model'),
        ),
    ]
