# Generated by Django 4.2.16 on 2025-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_denselayer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denselayer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense')], default='dense', max_length=100),
        ),
    ]
