# Generated by Django 4.2.16 on 2025-02-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rescaling'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rescaling',
            new_name='RescalingLayer',
        ),
    ]
