# Generated by Django 4.2.16 on 2025-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_denselayer_layer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denselayer',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='denselayer',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
