# Generated by Django 4.2.16 on 2025-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_rescaling_rescalinglayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescalinglayer',
            name='input_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rescalinglayer',
            name='input_y',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rescalinglayer',
            name='input_z',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
