# Generated by Django 4.2.16 on 2025-02-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0017_alter_denselayer_options_denselayer_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='denselayer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='denselayer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D')], default='dense', max_length=100),
        ),
    ]
