# Generated by Django 4.2.16 on 2025-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rescalinglayer_input_x_rescalinglayer_input_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescalinglayer',
            name='scale',
            field=models.CharField(max_length=100),
        ),
    ]
