# Generated by Django 4.2.16 on 2025-02-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0019_alter_denselayer_options_remove_denselayer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseModel',
            new_name='BaseLayer',
        ),
        migrations.RenameField(
            model_name='denselayer',
            old_name='basemodel_ptr',
            new_name='baselayer_ptr',
        ),
    ]
