# Generated by Django 4.2.16 on 2025-02-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_basemodel_baselayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conv2DLayer',
            fields=[
                ('baselayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baselayer')),
                ('filters', models.PositiveIntegerField(default=1)),
                ('kernel_size', models.PositiveIntegerField(default=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.baselayer',),
        ),
    ]
