# Generated by Django 4.2.16 on 2025-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_resizinglayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='denselayer',
            name='input_x',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
