# Generated by Django 4.2.16 on 2025-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_denselayer_input_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='resizinglayer',
            name='input_z',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resizinglayer',
            name='output_x',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resizinglayer',
            name='output_y',
            field=models.PositiveIntegerField(default=256),
            preserve_default=False,
        ),
    ]
