# Generated by Django 4.2.16 on 2025-02-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_resizinglayer_input_z_resizinglayer_output_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conv2dlayer',
            name='input_x',
        ),
        migrations.RemoveField(
            model_name='conv2dlayer',
            name='input_y',
        ),
        migrations.RemoveField(
            model_name='conv2dlayer',
            name='input_z',
        ),
        migrations.RemoveField(
            model_name='denselayer',
            name='input_x',
        ),
        migrations.RemoveField(
            model_name='flattenlayer',
            name='input_x',
        ),
        migrations.RemoveField(
            model_name='flattenlayer',
            name='input_y',
        ),
        migrations.RemoveField(
            model_name='rescalinglayer',
            name='input_x',
        ),
        migrations.RemoveField(
            model_name='rescalinglayer',
            name='input_y',
        ),
        migrations.RemoveField(
            model_name='rescalinglayer',
            name='input_z',
        ),
        migrations.RemoveField(
            model_name='resizinglayer',
            name='input_x',
        ),
        migrations.RemoveField(
            model_name='resizinglayer',
            name='input_y',
        ),
        migrations.RemoveField(
            model_name='resizinglayer',
            name='input_z',
        ),
        migrations.AddField(
            model_name='layer',
            name='input_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='input_y',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='input_z',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
