# Generated by Django 4.2.16 on 2025-02-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_evaluation_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='trained_on',
        ),
        migrations.AddField(
            model_name='model',
            name='trained_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_with', to='api.dataset'),
        ),
    ]
