# Generated by Django 4.2.16 on 2025-02-27 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_model_trained_on_model_trained_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='evaluated_accuracy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='model',
            name='evaluated_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_with', to='api.dataset'),
        ),
        migrations.AddField(
            model_name='model',
            name='trained_accuracy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
