# Generated by Django 4.2.16 on 2025-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_model_evaluated_on_tensorflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text')], default='Image', max_length=20),
        ),
    ]
