# Generated by Django 4.2.16 on 2025-03-06 16:32

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_model_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.element_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'avif', 'txt', 'doc', 'docx'])]),
        ),
    ]
