# Generated by Django 4.2.16 on 2025-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_element_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='training_progress',
            field=models.FloatField(default=0),
        ),
    ]
