# Generated by Django 4.2.16 on 2025-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_model_training_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_models', to='api.profile'),
        ),
    ]
