# Generated by Django 4.2.16 on 2025-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_model_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='training_progress',
        ),
        migrations.AddField(
            model_name='profile',
            name='training_progress',
            field=models.FloatField(default=0),
        ),
    ]
