# Generated by Django 4.2.16 on 2025-03-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_profile_evaluation_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextVectorizationLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
                ('max_tokens', models.PositiveIntegerField(default=10000, null=True)),
                ('standardize', models.CharField(choices=[('', ''), ('lower_and_strip_punctuation', 'lower_and_strip_punctuation'), ('lower', 'lower'), ('strip_punctuation', 'strip_punctuation')], default='lower_and_strip_punctuation', max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
    ]
