# Generated by Django 4.2.16 on 2025-03-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_textvectorizationlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
                ('max_features', models.PositiveIntegerField(default=10000)),
                ('output_dim', models.PositiveIntegerField(default=16)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
    ]
