# Generated by Django 4.2.16 on 2025-03-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_embeddinglayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embeddinglayer',
            old_name='max_features',
            new_name='max_tokens',
        ),
    ]
