# Generated by Django 4.2.16 on 2025-03-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_max_features_embeddinglayer_max_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAveragePooling1DLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
    ]
