# Generated by Django 4.2.16 on 2025-03-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
