# Generated by Django 4.2.16 on 2025-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_element_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='loss_function',
            field=models.CharField(blank=True, choices=[('binary_crossentropy', 'binary_crossentropy'), ('categorical_crossentropy', 'categorical_crossentropy'), ('sparse_categorical_crossentropy', 'sparse_categorical_crossentropy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='optimizer',
            field=models.CharField(blank=True, choices=[('adam', 'adam'), ('adagrad', 'adagrad'), ('adadelta', 'adadelta'), ('adamax', 'adamax'), ('sgd', 'sgd'), ('rmsprop', 'rmsprop')], max_length=100, null=True),
        ),
    ]
