# Generated by Django 4.2.16 on 2025-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_layer_activation_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='trained_accuracy',
        ),
        migrations.AddField(
            model_name='model',
            name='accuracy',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='loss',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='val_accuracy',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='val_loss',
            field=models.JSONField(null=True),
        ),
    ]
