# Generated by Django 4.2.16 on 2025-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_model_accuracy_alter_model_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textvectorizationlayer',
            name='output_sequence_length',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
