# Generated by Django 4.2.16 on 2025-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_textvectorizationlayer_output_sequence_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='words_count',
            field=models.PositiveIntegerField(default=256),
        ),
    ]
