# Generated by Django 4.2.16 on 2025-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_model_words_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='words_count',
            new_name='input_sequence_length',
        ),
    ]
