# Generated by Django 4.2.16 on 2025-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_words_count_model_input_sequence_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='element',
            name='text',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
