# Generated by Django 4.2.16 on 2025-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_profile_training_accuracy_alter_element_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_accuracy',
            field=models.FloatField(default=-1),
        ),
    ]
