# Generated by Django 4.2.16 on 2025-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_profile_training_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
