# Generated by Django 4.2.16 on 2025-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_layer_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='trainable',
            field=models.BooleanField(default=True),
        ),
    ]
