# Generated by Django 4.2.16 on 2025-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_layer_trainable'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='update_build',
            field=models.BooleanField(default=True),
        ),
    ]
