# Generated by Django 4.2.16 on 2025-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_layer_update_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_loss',
            field=models.FloatField(default=-1),
        ),
    ]
