# Generated by Django 4.2.16 on 2025-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_profile_training_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='accuracy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='model',
            name='loss',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='model',
            name='val_accuracy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='model',
            name='val_loss',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
