# Generated by Django 4.2.16 on 2025-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_model_accuracy_alter_model_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_time_remaining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
