# Generated by Django 4.2.16 on 2025-04-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_profile_training_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv2dlayer',
            name='padding',
            field=models.CharField(choices=[('valid', 'valid'), ('same', 'same')], default='valid', max_length=20),
        ),
    ]
