# Generated by Django 4.2.16 on 2025-04-11 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_conv2dlayer_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='val_split',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
