# Generated by Django 4.2.16 on 2025-04-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_randomrotationlayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomrotationlayer',
            name='factor',
            field=models.FloatField(),
        ),
    ]
