# Generated by Django 4.2.16 on 2025-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_mobilenetv2smalllayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D'), ('maxpool2d', 'MaxPool2d'), ('flatten', 'Flatten'), ('dropout', 'Dropout'), ('rescaling', 'Rescaling'), ('randomflip', 'RandomFlip'), ('resizing', 'Resizing'), ('textvectorization', 'TextVectorization'), ('embedding', 'Embedding'), ('globalaveragepooling1d', 'GlobalAveragePooling1D'), ('mobilenetv2', 'MobileNetV2'), ('mobilenetv2small', 'MobileNetV2Small')], max_length=100),
        ),
    ]
