# Generated by Django 4.2.16 on 2025-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_layer_layer_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileNetV2SmallLayer',
            new_name='MobileNetV2_96x96Layer',
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D'), ('maxpool2d', 'MaxPool2d'), ('flatten', 'Flatten'), ('dropout', 'Dropout'), ('rescaling', 'Rescaling'), ('randomflip', 'RandomFlip'), ('resizing', 'Resizing'), ('textvectorization', 'TextVectorization'), ('embedding', 'Embedding'), ('globalaveragepooling1d', 'GlobalAveragePooling1D'), ('mobilenetv2', 'MobileNetV2'), ('mobilenetv2_96x96', 'MobileNetV2S_96x96')], max_length=100),
        ),
    ]
