# Generated by Django 4.2.16 on 2025-04-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_rename_mobilenetv2smalllayer_mobilenetv2_96x96layer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNetV2_32x32Layer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.layer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.layer',),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('dense', 'Dense'), ('conv2d', 'Conv2D'), ('maxpool2d', 'MaxPool2d'), ('flatten', 'Flatten'), ('dropout', 'Dropout'), ('rescaling', 'Rescaling'), ('randomflip', 'RandomFlip'), ('resizing', 'Resizing'), ('textvectorization', 'TextVectorization'), ('embedding', 'Embedding'), ('globalaveragepooling1d', 'GlobalAveragePooling1D'), ('mobilenetv2', 'MobileNetV2'), ('mobilenetv2_96x96', 'MobileNetV2_96x96'), ('mobilenetv2_32x32', 'MobileNetV2_32x32')], max_length=100),
        ),
    ]
