# Generated by Django 4.2.16 on 2025-05-10 16:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_mobilenetv2_32x32layer_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.model_image_path),
        ),
        migrations.AlterField(
            model_name='model',
            name='imageSmall',
            field=models.ImageField(null=True, upload_to=api.models.model_image_path),
        ),
    ]
