# Generated by Django 4.2.16 on 2025-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_model_image_alter_model_imagesmall'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='processing_data_progress',
            field=models.FloatField(default=0),
        ),
    ]
