# Generated by Django 4.2.16 on 2025-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_profile_deleting_elements_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creating_elements_progress',
            field=models.FloatField(default=0),
        ),
    ]
