# Generated by Django 4.2.16 on 2025-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_profile_creating_elements_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
