# Generated by Django 4.2.16 on 2025-06-02 10:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.profile_image_file_path),
        ),
    ]
